#!/usr/bin/env bash

set -euo pipefail

# 设置 Java 代理
export JAVA_TOOL_OPTIONS='-Dhttp.proxyHost=proxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy -Dhttps.proxyPort=8080'

# 安装前端依赖
yarn install


# 下载 ClojureScript 编译所需的 jar 包
npx shadow-cljs deps
